name: Git tests

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  pytest:
    runs-on: self-hosted
    timeout-minutes: 1
    container: kel.osll.ru:8083/docker/ubuntu:20.04
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: |
         echo "ok"
      shell: bash
